### ISSUE TITLE
Update aws-sdk version

### ISSUE THREAD

**Issue by jaximan** [fastlane-community/fastlane-plugin-s3#71]
Hi here!

In my project, I use aws-sdk-s3, which is v3 version of api. Your incredible plugin depends on aws-sdk v2 `~> 2.3`, which is incompatible by gem dependency resolver. Would you be open for PR with bump version of aws sdk and necessary code changes? Or it could be a reason why version bump is not acceptable?

Thanks!

**Comment by joshdholtz** [comment]
Fixed in version `1.170.0` 🚀
