### ISSUE TITLE
Wrong number of arguments with v2.0.0

### ISSUE THREAD

**Issue by felginep** [fastlane-community/fastlane-plugin-s3#97]
With the new version 2.0.0, the method `upload_file` expects 9 arguments but is called with only 7.

In version **1.8.3**
https://github.com/fastlane-community/fastlane-plugin-s3/blob/20ae0fe44291408756ec4ec7bda43ea28be59c50/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb#L503

In version **2.0.0** 
https://github.com/fastlane-community/fastlane-plugin-s3/blob/b2a05da1efa554d109c0ec72031ab7e57ed2521c/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb#L559

The call site does not change and still pass only 7 arguments: https://github.com/fastlane-community/fastlane-plugin-s3/blob/b2a05da1efa554d109c0ec72031ab7e57ed2521c/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb#L529

Here is a callstack
```
ArgumentError: [!] wrong number of arguments (given 7, expected 9)
  .../fastlane-plugin-aws_s3-2.0.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:559:in `upload_file'
  .../fastlane-plugin-aws_s3-2.0.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:529:in `block in upload_files'
  .../fastlane-plugin-aws_s3-2.0.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:524:in `each'
  .../fastlane-plugin-aws_s3-2.0.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:524:in `upload_files'
  .../fastlane-plugin-aws_s3-2.0.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:103:in `run'
  .../fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  .../fastlane-2.178.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  .../fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  .../fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  .../fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  .../fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  .../fastlane-2.178.0/fastlane/lib/fastlane/other_action.rb:23:in `method_missing'
```

**Comment by schwmi** [comment]
Have the same error - I am calling `aws_s3` via:
```
        aws_s3(
              bucket: "…",
              region: "…",
              files: [".zip"],
              app_directory: "…"
        )
```

using it it distribute a zipped Mac app. This used to work in previous versions.

**Comment by joshdholtz** [comment]
Ah sorry! Will fix will fix
